import Head from 'next/head'
import HomeComp from '@/components/HomeComp'




export default function Home() {
  return (
    <>
      <Head>
        <title>rehab portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="../public/assets/images/logo.png" />
      </Head>
      <main >
      <HomeComp/>
     
      </main>
    </>
  )
}
